FROM node:22 AS base
WORKDIR /usr/src/app
COPY ./build .
COPY ./package.json .
RUN npm install --force --production

FROM node:22-alpine AS final 
WORKDIR /usr/src/app
COPY --from=base /usr/src/app .
RUN apk add --no-cache openocd nodejs
CMD ["node", "index.js"]